### ISSUE TITLE
Материалы с курсеры

### ISSUE THREAD

**Issue by BceBoJlog** [momsspaghettti/coursera-golang-webservices-2#1]
Здравствуйте.  
Я прохожу обучение по первой части курса. Недавно Курсера убрала доступ ко всем курсам МФТИ. При этом доступ, как я понимаю, остался у тех, кто ранее проходил этот курс.
Не могли бы вы поделиться конспектами курса Golang_Webservices_2? Интересуют лекции в pdf за каждую неделю. Курс вроде как бесплатный, лицензию вы не нарушите, насколько я понимаю.

**Comment by momsspaghettti** [comment]
Здравствуйте, напиши свою почту, я отправлю тебе

**Comment by BceBoJlog** [comment]
bcebojlog \@ yandex.ru

**Comment by BceBoJlog** [comment]
спасибо!
